services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      SQLITE_PATH: /data/database.sqlite
      CORS_ORIGIN: "http://34.44.161.245,http://127.0.0.1:8080,http://localhost,http://127.0.0.1,http://localhost:5173"
    volumes:
      - backend-data:/data

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  backend-data:
